name: Wasm pack test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: wasm-pack build
      - run: wasm-pack test --firefox --headless
